SET DEFINE OFF;
SET SERVEROUTPUT ON;



BEGIN
  FOR t IN (SELECT table_name FROM user_tables
            WHERE table_name IN (
              'PURCHASEDETAIL','PURCHASEORDER',
              'ORDER_LINE','ORDERS','PAYMENT',
              'INGREDIENT_ITEM','INGREDIENT','MENUITEM',
              'STAFF_ROLE','STAFF','ROLE',
              'RESERVATION','CUSTOMER','SUPPLIER','HELP'
            ))
  LOOP
    EXECUTE IMMEDIATE 'DROP TABLE '||t.table_name||' CASCADE CONSTRAINTS PURGE';
  END LOOP;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  FOR s IN (SELECT sequence_name FROM user_sequences
            WHERE sequence_name IN (
              'SEQ_SUPPLIER','SEQ_CUSTOMER','SEQ_ROLE','SEQ_STAFF',
              'SEQ_MENUITEM','SEQ_INGREDIENT','SEQ_PAYMENT','SEQ_ORDER',
              'SEQ_PURCHASEORDER','SEQ_RESERVATION'
            ))
  LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE '||s.sequence_name;
  END LOOP;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  FOR tr IN (SELECT trigger_name FROM user_triggers
             WHERE trigger_name IN (
               'TRG_SUPPLIER_BI','TRG_CUSTOMER_BI','TRG_ROLE_BI','TRG_STAFF_BI',
               'TRG_MENUITEM_BI','TRG_INGREDIENT_BI','TRG_PAYMENT_BI','TRG_ORDERS_BI',
               'TRG_PO_BI','TRG_RESERVATION_BI',
               'TRG_ORDERLINE_DEDUCT_STOCK','TRG_PURCHASE_ADD_STOCK'
             ))
  LOOP
    EXECUTE IMMEDIATE 'DROP TRIGGER '||tr.trigger_name;
  END LOOP;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  FOR v IN (SELECT view_name FROM user_views
            WHERE view_name IN ('VW_MENU','VW_STOCK_STATUS','VW_ORDER_SUMMARY'))
  LOOP
    EXECUTE IMMEDIATE 'DROP VIEW '||v.view_name;
  END LOOP;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION FN_ORDER_TOTAL';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE SP_PLACE_ORDER';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE SP_RECEIVE_PO';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/


-- ============================================================
-- TABLES
-- ============================================================

CREATE TABLE HELP (
  TOPIC VARCHAR2(50) NOT NULL,
  SEQ   NUMBER       NOT NULL,
  INFO  VARCHAR2(200),
  CONSTRAINT PK_HELP PRIMARY KEY (TOPIC, SEQ)
);

CREATE TABLE SUPPLIER (
  SUPPLIERID   NUMBER        NOT NULL,
  NAME         VARCHAR2(100) NOT NULL,
  CONTACT_INFO VARCHAR2(200),
  CONSTRAINT PK_SUPPLIER PRIMARY KEY (SUPPLIERID),
  CONSTRAINT UQ_SUPPLIER_NAME UNIQUE (NAME)
);

CREATE TABLE CUSTOMER (
  CUSTOMERID NUMBER        NOT NULL,
  NAME       VARCHAR2(100) NOT NULL,
  PHONE      VARCHAR2(20),
  EMAIL      VARCHAR2(120),
  CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMERID)
);

CREATE TABLE ROLE (
  ROLEID      NUMBER        NOT NULL,
  ROLENAME    VARCHAR2(50)  NOT NULL,
  DESCRIPTION VARCHAR2(200),
  CONSTRAINT PK_ROLE PRIMARY KEY (ROLEID),
  CONSTRAINT UQ_ROLE_NAME UNIQUE (ROLENAME)
);

CREATE TABLE STAFF (
  STAFFID NUMBER        NOT NULL,
  NAME    VARCHAR2(100) NOT NULL,
  PHONE   VARCHAR2(20),
  ADDRESS VARCHAR2(200),
  CONSTRAINT PK_STAFF PRIMARY KEY (STAFFID)
);

CREATE TABLE STAFF_ROLE (
  STAFFID NUMBER NOT NULL,
  ROLEID  NUMBER NOT NULL,
  CONSTRAINT PK_STAFF_ROLE PRIMARY KEY (STAFFID, ROLEID),
  CONSTRAINT FK_SR_STAFF FOREIGN KEY (STAFFID) REFERENCES STAFF(STAFFID),
  CONSTRAINT FK_SR_ROLE  FOREIGN KEY (ROLEID)  REFERENCES ROLE(ROLEID)
);

CREATE TABLE MENUITEM (
  MENUITEMID  NUMBER         NOT NULL,
  NAME        VARCHAR2(100)  NOT NULL,
  DESCRIPTION VARCHAR2(200),
  PRICE       NUMBER(8,2)    NOT NULL,
  CONSTRAINT PK_MENUITEM PRIMARY KEY (MENUITEMID),
  CONSTRAINT CK_MENU_PRICE CHECK (PRICE >= 0)
);

CREATE TABLE INGREDIENT (
  INGREDIENTID  NUMBER        NOT NULL,
  NAME          VARCHAR2(100) NOT NULL,
  UNIT          VARCHAR2(20)  DEFAULT 'g',
  STOCK_LEVEL   NUMBER        DEFAULT 0,
  REORDER_LEVEL NUMBER        DEFAULT 0,
  SUPPLIERID    NUMBER,
  CONSTRAINT PK_INGREDIENT PRIMARY KEY (INGREDIENTID),
  CONSTRAINT FK_ING_SUPPLIER FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER(SUPPLIERID),
  CONSTRAINT CK_ING_STOCK CHECK (STOCK_LEVEL >= 0),
  CONSTRAINT CK_ING_REORDER CHECK (REORDER_LEVEL >= 0)
);

CREATE TABLE INGREDIENT_ITEM (
  INGREDIENTID NUMBER NOT NULL,
  MENUITEMID   NUMBER NOT NULL,
  QUANTITY     NUMBER DEFAULT 0,
  CONSTRAINT PK_ING_ITEM PRIMARY KEY (INGREDIENTID, MENUITEMID),
  CONSTRAINT FK_II_ING  FOREIGN KEY (INGREDIENTID) REFERENCES INGREDIENT(INGREDIENTID),
  CONSTRAINT FK_II_MENU FOREIGN KEY (MENUITEMID)   REFERENCES MENUITEM(MENUITEMID),
  CONSTRAINT CK_II_QTY CHECK (QUANTITY >= 0)
);

CREATE TABLE PAYMENT (
  PAYMENTID      NUMBER        NOT NULL,
  PAYMENTMETHOD  VARCHAR2(30)  NOT NULL,
  AMOUNT         NUMBER(10,2)  NOT NULL,
  PAYMENTSTATUS  VARCHAR2(20)  DEFAULT 'PAID',
  CONSTRAINT PK_PAYMENT PRIMARY KEY (PAYMENTID),
  CONSTRAINT CK_PAY_AMOUNT CHECK (AMOUNT >= 0),
  CONSTRAINT CK_PAY_STATUS CHECK (PAYMENTSTATUS IN ('PAID','PENDING','FAILED','REFUNDED'))
);

CREATE TABLE ORDERS (
  ORDERID       NUMBER        NOT NULL,
  ORDERDATETIME TIMESTAMP(6)  DEFAULT SYSTIMESTAMP,
  ORDERTYPE     VARCHAR2(20)  DEFAULT 'DINE_IN',
  TABLENO       NUMBER,
  STAFFID       NUMBER,
  PAYMENTID     NUMBER,
  CONSTRAINT PK_ORDERS PRIMARY KEY (ORDERID),
  CONSTRAINT FK_ORD_STAFF FOREIGN KEY (STAFFID) REFERENCES STAFF(STAFFID),
  CONSTRAINT FK_ORD_PAY   FOREIGN KEY (PAYMENTID) REFERENCES PAYMENT(PAYMENTID),
  CONSTRAINT UQ_ORDERS_PAYMENT UNIQUE (PAYMENTID),
  CONSTRAINT CK_ORDER_TYPE CHECK (ORDERTYPE IN ('DINE_IN','TAKEAWAY','DELIVERY','PREORDER'))
);

CREATE TABLE ORDER_LINE (
  ORDERID    NUMBER NOT NULL,
  MENUITEMID NUMBER NOT NULL,
  QUANTITY   NUMBER NOT NULL,
  UNITPRICE  NUMBER(8,2) NOT NULL,
  CONSTRAINT PK_ORDER_LINE PRIMARY KEY (ORDERID, MENUITEMID),
  CONSTRAINT FK_OL_ORDER FOREIGN KEY (ORDERID) REFERENCES ORDERS(ORDERID) ON DELETE CASCADE,
  CONSTRAINT FK_OL_MENU  FOREIGN KEY (MENUITEMID) REFERENCES MENUITEM(MENUITEMID),
  CONSTRAINT CK_OL_QTY CHECK (QUANTITY > 0),
  CONSTRAINT CK_OL_PRICE CHECK (UNITPRICE >= 0)
);

CREATE TABLE PURCHASEORDER (
  PURCHASEORDERID NUMBER NOT NULL,
  ORDERDATE       DATE   DEFAULT SYSDATE,
  SUPPLIERID      NUMBER,
  STAFFID         NUMBER,
  CONSTRAINT PK_PO PRIMARY KEY (PURCHASEORDERID),
  CONSTRAINT FK_PO_SUP FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER(SUPPLIERID),
  CONSTRAINT FK_PO_STAFF FOREIGN KEY (STAFFID) REFERENCES STAFF(STAFFID)
);

CREATE TABLE PURCHASEDETAIL (
  PURCHASEORDERID NUMBER NOT NULL,
  INGREDIENTID    NUMBER NOT NULL,
  QUANTITY        NUMBER NOT NULL,
  PURCHASEPRICE   NUMBER(8,2) NOT NULL,
  CONSTRAINT PK_PD PRIMARY KEY (PURCHASEORDERID, INGREDIENTID),
  CONSTRAINT FK_PD_PO  FOREIGN KEY (PURCHASEORDERID) REFERENCES PURCHASEORDER(PURCHASEORDERID) ON DELETE CASCADE,
  CONSTRAINT FK_PD_ING FOREIGN KEY (INGREDIENTID) REFERENCES INGREDIENT(INGREDIENTID),
  CONSTRAINT CK_PD_QTY CHECK (QUANTITY > 0),
  CONSTRAINT CK_PD_PRICE CHECK (PURCHASEPRICE >= 0)
);

CREATE TABLE RESERVATION (
  RESERVATIONID   NUMBER NOT NULL,
  CUSTOMERID      NUMBER,
  RESERVATIONDATE DATE   NOT NULL,
  RESERVATIONTIME VARCHAR2(10),
  NOOFGUESTS      NUMBER NOT NULL,
  CONSTRAINT PK_RES PRIMARY KEY (RESERVATIONID),
  CONSTRAINT FK_RES_CUST FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID),
  CONSTRAINT CK_RES_GUESTS CHECK (NOOFGUESTS > 0)
);


-- ============================================================
-- SEQUENCES
-- ============================================================

CREATE SEQUENCE SEQ_SUPPLIER      START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CUSTOMER      START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ROLE          START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_STAFF         START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MENUITEM      START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_INGREDIENT    START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PAYMENT       START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ORDER         START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PURCHASEORDER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RESERVATION   START WITH 1 INCREMENT BY 1;


-- ============================================================
-- AUTO-ID TRIGGERS
-- ============================================================

CREATE OR REPLACE TRIGGER TRG_SUPPLIER_BI
BEFORE INSERT ON SUPPLIER FOR EACH ROW
BEGIN
  IF :NEW.SUPPLIERID IS NULL THEN :NEW.SUPPLIERID := SEQ_SUPPLIER.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_CUSTOMER_BI
BEFORE INSERT ON CUSTOMER FOR EACH ROW
BEGIN
  IF :NEW.CUSTOMERID IS NULL THEN :NEW.CUSTOMERID := SEQ_CUSTOMER.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ROLE_BI
BEFORE INSERT ON ROLE FOR EACH ROW
BEGIN
  IF :NEW.ROLEID IS NULL THEN :NEW.ROLEID := SEQ_ROLE.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_STAFF_BI
BEFORE INSERT ON STAFF FOR EACH ROW
BEGIN
  IF :NEW.STAFFID IS NULL THEN :NEW.STAFFID := SEQ_STAFF.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_MENUITEM_BI
BEFORE INSERT ON MENUITEM FOR EACH ROW
BEGIN
  IF :NEW.MENUITEMID IS NULL THEN :NEW.MENUITEMID := SEQ_MENUITEM.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_INGREDIENT_BI
BEFORE INSERT ON INGREDIENT FOR EACH ROW
BEGIN
  IF :NEW.INGREDIENTID IS NULL THEN :NEW.INGREDIENTID := SEQ_INGREDIENT.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PAYMENT_BI
BEFORE INSERT ON PAYMENT FOR EACH ROW
BEGIN
  IF :NEW.PAYMENTID IS NULL THEN :NEW.PAYMENTID := SEQ_PAYMENT.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ORDERS_BI
BEFORE INSERT ON ORDERS FOR EACH ROW
BEGIN
  IF :NEW.ORDERID IS NULL THEN :NEW.ORDERID := SEQ_ORDER.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PO_BI
BEFORE INSERT ON PURCHASEORDER FOR EACH ROW
BEGIN
  IF :NEW.PURCHASEORDERID IS NULL THEN :NEW.PURCHASEORDERID := SEQ_PURCHASEORDER.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_RESERVATION_BI
BEFORE INSERT ON RESERVATION FOR EACH ROW
BEGIN
  IF :NEW.RESERVATIONID IS NULL THEN :NEW.RESERVATIONID := SEQ_RESERVATION.NEXTVAL; END IF;
END;
/


-- ============================================================
-- BUSINESS LOGIC TRIGGERS
-- ============================================================

CREATE OR REPLACE TRIGGER TRG_ORDERLINE_DEDUCT_STOCK
AFTER INSERT ON ORDER_LINE
FOR EACH ROW
DECLARE
  v_neg_cnt NUMBER;
BEGIN
  UPDATE INGREDIENT i
     SET i.STOCK_LEVEL = i.STOCK_LEVEL - (
         SELECT ii.QUANTITY * :NEW.QUANTITY
           FROM INGREDIENT_ITEM ii
          WHERE ii.INGREDIENTID = i.INGREDIENTID
            AND ii.MENUITEMID = :NEW.MENUITEMID
     )
   WHERE EXISTS (
     SELECT 1 FROM INGREDIENT_ITEM ii
      WHERE ii.INGREDIENTID = i.INGREDIENTID
        AND ii.MENUITEMID = :NEW.MENUITEMID
   );

  SELECT COUNT(*) INTO v_neg_cnt
  FROM INGREDIENT WHERE STOCK_LEVEL < 0;

  IF v_neg_cnt > 0 THEN
    RAISE_APPLICATION_ERROR(-20001, 'Insufficient ingredient stock for this order.');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PURCHASE_ADD_STOCK
AFTER INSERT ON PURCHASEDETAIL
FOR EACH ROW
BEGIN
  UPDATE INGREDIENT
     SET STOCK_LEVEL = STOCK_LEVEL + :NEW.QUANTITY
   WHERE INGREDIENTID = :NEW.INGREDIENTID;
END;
/


-- ============================================================
-- VIEWS
-- ============================================================

CREATE OR REPLACE VIEW VW_MENU AS
SELECT m.MENUITEMID, m.NAME, m.DESCRIPTION, m.PRICE
FROM MENUITEM m;

CREATE OR REPLACE VIEW VW_STOCK_STATUS AS
SELECT i.INGREDIENTID, i.NAME, i.UNIT, i.STOCK_LEVEL, i.REORDER_LEVEL,
       CASE WHEN i.STOCK_LEVEL <= i.REORDER_LEVEL THEN 'REORDER' ELSE 'OK' END AS STATUS
FROM INGREDIENT i;

CREATE OR REPLACE VIEW VW_ORDER_SUMMARY AS
SELECT o.ORDERID, o.ORDERDATETIME, o.ORDERTYPE, o.TABLENO,
       s.NAME AS STAFF_NAME,
       p.PAYMENTMETHOD, p.PAYMENTSTATUS, p.AMOUNT
FROM ORDERS o
LEFT JOIN STAFF s ON s.STAFFID = o.STAFFID
LEFT JOIN PAYMENT p ON p.PAYMENTID = o.PAYMENTID;


-- ============================================================
-- FUNCTION & STORED PROCEDURES
-- ============================================================

CREATE OR REPLACE FUNCTION FN_ORDER_TOTAL(p_orderid NUMBER)
RETURN NUMBER IS
  v_total NUMBER := 0;
BEGIN
  SELECT NVL(SUM(QUANTITY * UNITPRICE), 0)
    INTO v_total
    FROM ORDER_LINE
   WHERE ORDERID = p_orderid;
  RETURN v_total;
END;
/

CREATE OR REPLACE PROCEDURE SP_PLACE_ORDER(
  p_ordertype     IN  VARCHAR2,
  p_tableno       IN  NUMBER,
  p_staffid       IN  NUMBER,
  p_paymentmethod IN  VARCHAR2,
  p_paymentstatus IN  VARCHAR2,
  p_orderid       OUT NUMBER
) IS
  v_paymentid NUMBER;
BEGIN
  INSERT INTO PAYMENT(paymentmethod, amount, paymentstatus)
  VALUES (p_paymentmethod, 0, NVL(p_paymentstatus,'PAID'))
  RETURNING paymentid INTO v_paymentid;

  INSERT INTO ORDERS(orderdatetime, ordertype, tableno, staffid, paymentid)
  VALUES (SYSTIMESTAMP, NVL(p_ordertype,'DINE_IN'), p_tableno, p_staffid, v_paymentid)
  RETURNING orderid INTO p_orderid;

  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_RECEIVE_PO(
  p_supplierid IN  NUMBER,
  p_staffid    IN  NUMBER,
  p_poid       OUT NUMBER
) IS
BEGIN
  INSERT INTO PURCHASEORDER(orderdate, supplierid, staffid)
  VALUES (SYSDATE, p_supplierid, p_staffid)
  RETURNING purchaseorderid INTO p_poid;
  COMMIT;
END;
/


-- ============================================================
-- SEED DATA
-- ============================================================

INSERT INTO HELP(topic, seq, info) VALUES ('RUN',  1, 'Use F5 to run this script. SET DEFINE OFF prevents & prompt.');
INSERT INTO HELP(topic, seq, info) VALUES ('TIPS', 1, 'Re-run safe: script drops & recreates objects.');
INSERT INTO HELP(topic, seq, info) VALUES ('TIPS', 2, 'Order line uses UNITPRICE. Keep naming consistent.');

INSERT INTO SUPPLIER(name, contact_info) VALUES ('GreenFarm Supplies', 'greenfarm@example.com | +60-12-1111111');
INSERT INTO SUPPLIER(name, contact_info) VALUES ('Organic Hub',        'organichub@example.com | +60-12-2222222');
INSERT INTO SUPPLIER(name, contact_info) VALUES ('Spice & Beans Co.',  'spicebeans@example.com | +60-12-3333333');

INSERT INTO ROLE(rolename, description) VALUES ('Manager', 'Manage operations, approve purchase orders, handle escalations.');
INSERT INTO ROLE(rolename, description) VALUES ('Cashier', 'Handle payments and order checkout.');
INSERT INTO ROLE(rolename, description) VALUES ('Kitchen', 'Prepare menu items and manage ingredient usage.');
INSERT INTO ROLE(rolename, description) VALUES ('Waiter',  'Serve dine-in customers and table operations.');

INSERT INTO STAFF(name, phone, address) VALUES ('Aina Rahman', '012-9000001', 'Sri Hartamas');
INSERT INTO STAFF(name, phone, address) VALUES ('Daniel Lee',  '012-9000002', 'Mont Kiara');
INSERT INTO STAFF(name, phone, address) VALUES ('Siti Nur',    '012-9000003', 'TTDI');

INSERT INTO STAFF_ROLE(staffid, roleid) VALUES (1, 1);
INSERT INTO STAFF_ROLE(staffid, roleid) VALUES (2, 2);
INSERT INTO STAFF_ROLE(staffid, roleid) VALUES (3, 3);

INSERT INTO CUSTOMER(name, phone, email) VALUES ('Eva Ceryana',  '+60-12-8888888', 'eva@example.com');
INSERT INTO CUSTOMER(name, phone, email) VALUES ('Amir Hassan',  '+60-12-7777777', 'amir@example.com');

INSERT INTO MENUITEM(name, description, price) VALUES ('Shrooms Asada',   'Flour tortilla, mushroom asada, rice, beans, slaw.', 28.00);
INSERT INTO MENUITEM(name, description, price) VALUES ('Spicy Asian Taco', 'Taco with spicy tofu and fresh veg.',                18.00);
INSERT INTO MENUITEM(name, description, price) VALUES ('Protein Packed',   'Tempeh+tofu+quinoa+hummus bowl.',                    20.00);

INSERT INTO INGREDIENT(name, unit, stock_level, reorder_level, supplierid) VALUES ('Flour Tortilla', 'pcs', 200,   50,   1);
INSERT INTO INGREDIENT(name, unit, stock_level, reorder_level, supplierid) VALUES ('Mushroom Asada', 'g',   30000, 5000, 2);
INSERT INTO INGREDIENT(name, unit, stock_level, reorder_level, supplierid) VALUES ('Brown Rice',     'g',   40000, 8000, 1);
INSERT INTO INGREDIENT(name, unit, stock_level, reorder_level, supplierid) VALUES ('Black Beans',    'g',   35000, 7000, 3);
INSERT INTO INGREDIENT(name, unit, stock_level, reorder_level, supplierid) VALUES ('Slaw',           'g',   15000, 3000, 1);
INSERT INTO INGREDIENT(name, unit, stock_level, reorder_level, supplierid) VALUES ('Spicy Tofu',     'g',   20000, 4000, 2);
INSERT INTO INGREDIENT(name, unit, stock_level, reorder_level, supplierid) VALUES ('Quinoa',         'g',   15000, 3000, 1);
INSERT INTO INGREDIENT(name, unit, stock_level, reorder_level, supplierid) VALUES ('Hummus',         'g',   12000, 2000, 1);

INSERT INTO INGREDIENT_ITEM(ingredientid, menuitemid, quantity) VALUES (1, 1, 1);
INSERT INTO INGREDIENT_ITEM(ingredientid, menuitemid, quantity) VALUES (2, 1, 180);
INSERT INTO INGREDIENT_ITEM(ingredientid, menuitemid, quantity) VALUES (3, 1, 150);
INSERT INTO INGREDIENT_ITEM(ingredientid, menuitemid, quantity) VALUES (4, 1, 120);
INSERT INTO INGREDIENT_ITEM(ingredientid, menuitemid, quantity) VALUES (5, 1, 60);

INSERT INTO INGREDIENT_ITEM(ingredientid, menuitemid, quantity) VALUES (1, 2, 1);
INSERT INTO INGREDIENT_ITEM(ingredientid, menuitemid, quantity) VALUES (6, 2, 120);
INSERT INTO INGREDIENT_ITEM(ingredientid, menuitemid, quantity) VALUES (5, 2, 40);

INSERT INTO INGREDIENT_ITEM(ingredientid, menuitemid, quantity) VALUES (7, 3, 120);
INSERT INTO INGREDIENT_ITEM(ingredientid, menuitemid, quantity) VALUES (8, 3, 60);
INSERT INTO INGREDIENT_ITEM(ingredientid, menuitemid, quantity) VALUES (6, 3, 80);

INSERT INTO RESERVATION(customerid, reservationdate, reservationtime, noofguests)
VALUES (1, TO_DATE('2025-12-30','YYYY-MM-DD'), '19:30', 4);

-- Sample order with automatic stock deduction via trigger
DECLARE
  v_orderid NUMBER;
BEGIN
  SP_PLACE_ORDER('DINE_IN', 5, 2, 'CARD', 'PAID', v_orderid);

  INSERT INTO ORDER_LINE(orderid, menuitemid, quantity, unitprice) VALUES (v_orderid, 1, 1, 28.00);
  INSERT INTO ORDER_LINE(orderid, menuitemid, quantity, unitprice) VALUES (v_orderid, 3, 1, 20.00);

  UPDATE PAYMENT
     SET AMOUNT = FN_ORDER_TOTAL(v_orderid)
   WHERE PAYMENTID = (SELECT PAYMENTID FROM ORDERS WHERE ORDERID = v_orderid);

  COMMIT;
END;
/

-- Sample purchase order with automatic stock restoration via trigger
DECLARE
  v_poid NUMBER;
BEGIN
  SP_RECEIVE_PO(1, 1, v_poid);
  INSERT INTO PURCHASEDETAIL(purchaseorderid, ingredientid, quantity, purchaseprice) VALUES (v_poid, 2, 3000, 0.05);
  COMMIT;
END;
/


-- ============================================================
-- VERIFICATION QUERIES
-- ============================================================

SELECT * FROM VW_MENU ORDER BY MENUITEMID;
SELECT * FROM VW_STOCK_STATUS ORDER BY STATUS, INGREDIENTID;
SELECT * FROM VW_ORDER_SUMMARY ORDER BY ORDERID DESC;

SELECT s.staffid, s.name AS staff_name, r.rolename
FROM staff s
JOIN staff_role sr ON sr.staffid = s.staffid
JOIN role r ON r.roleid = sr.roleid
ORDER BY s.staffid, r.roleid;

SELECT m.menuitemid, m.name AS menu_name,
       i.name AS ingredient_name, ii.quantity, i.unit
FROM menuitem m
JOIN ingredient_item ii ON ii.menuitemid = m.menuitemid
JOIN ingredient i ON i.ingredientid = ii.ingredientid
ORDER BY m.menuitemid, i.ingredientid;
